### ISSUE TITLE
require-ascii.py syntax is incompatible with python 3

### ISSUE THREAD

**Issue by dstull** [jumanjihouse/pre-commit-hooks#26]
when running with require-ascii enabled, on python version 3.6, on OSX, the following error is observed:
Check file encoding.........................................................Failed
hookid: require-ascii

File "/Users/dstull/.cache/pre-commit/repojmex2sqj/py_env-python3.6/bin/require-ascii.py", line 26
    print result.ljust(8) + filename.ljust(50),
               ^
SyntaxError: invalid syntax

I believe in python 3, print is a function and perhaps a wrapping of this line with `()` would fix it

confirmed - this makes the error go away:
```
    print(result.ljust(8) + filename.ljust(50)),
    print(dict)
```

**Comment by dstull** [comment]
that worked - thanks!

**Comment by jumanjiman** [comment]
> that worked - thanks!

thanks for confirming!
