### ISSUE TITLE
This check needs shfmt from ...

### ISSUE THREAD

**Issue by kenorb** [jumanjihouse/pre-commit-hooks#58]
```
Check shell style with shfmt................................................Failed
- hook id: shfmt
- exit code: 1

This check needs shfmt from https://github.com/mvdan/sh/releases
This check needs shfmt from https://github.com/mvdan/sh/releases
```

Build: [786160960](https://github.com/EA31337/EA-Tester/runs/786160960?check_suite_focus=true#step:4:91)

I'm using [pre-commit/action@v2.0.0](https://github.com/pre-commit/action)

It works on my local, but not on GitHub Actions. So I'm not sure what's the problem.

**Comment by jumanjiman** [comment]
@kenorb 

The error means the runtime environment needs to install the `shfmt` binary.

https://github.com/mvdan/sh/releases provides statically-linked binaries that can be installed via something like this:

```shell
SHFMT_VERSION="v3.1.1"
DOWNLOAD_URL="https://github.com/mvdan/sh/releases/download/${SHFMT_VERSION}/shfmt_${SHFMT_VERSION}_linux_amd64"

INSTALL_PATH="/usr/local/bin/shfmt"

curl -L -ssL -o "${INSTALL_PATH}" "${DOWNLOAD_URL}"
chmod 0755 "${INSTALL_PATH}"
```

hth,
-paul

____

The [pre-commit-hook code in question](https://github.com/jumanjihouse/pre-commit-hooks/blob/7be5db3371497bce9580bb657f8ed5bd909a8d4c/pre_commit_hooks/shfmt#L13-L16) is:

```shell
if ! command -v shfmt >/dev/null 2>&1; then
  echo 'This check needs shfmt from https://github.com/mvdan/sh/releases'
  exit 1
fi
```

**Comment by kenorb** [comment]
Ah, ok, I thought `pre-commit` should install all the dependencies for you automatically as it works with others (such as Markdownlint), but maybe it only works for the Python libraries and other tools are already installed. I'll have a look in more details how the installation works.

Meanwhile I'm going install `shfmt` manually before running `pre-commit`.

Thanks.
