### ISSUE TITLE
require-ascii: Allow extended ASCII characters

### ISSUE THREAD

**Issue by kenorb** [jumanjihouse/pre-commit-hooks#63]
```
Check file encoding.........................................................Failed
- hook id: require-ascii
- exit code: 1

README.md: line 270 column 11 character "©" (decimal 169)
```

I'd like to exclude the copyright character from README ("©"), is that possible, without disabling the whole hook?

**Comment by kenorb** [comment]
Also, isn't © part of ASCII, but extended?

See: https://theasciicode.com.ar/extended-ascii-code/copyright-symbol-ascii-code-184.html

**Comment by jumanjiman** [comment]
> Also, isn't © part of ASCII, but extended?

great point!

I've opened https://github.com/jumanjihouse/pre-commit-hooks/issues/62 to allow the whole set of extended ascii characters.

**Comment by jumanjiman** [comment]
@kenorb 

Rev 2.1.4 allows the whole extended ascii set
